module.exports ={
    colors:{
        col1:"white",
        text1:"red",
        text2:'grey',
        text3:'black',
    },
    titles:{
        title1:40,
        btntxt:20,
    },
    btn1:{
        width:'80%',
        height:50,
        backgroundColor:"red",
        borderRadius:10,
        alignItems:'center',
        justifyContent:"center",
        elevation:10,
        color:'white',
    },
    hr80:{
        width:'80%',
        borderBottomColor:'#f0e16e',
        borderBottomWidth:1,
        marginVertical:20,
    },
    hr81:{
        width:'80%',
        borderBottomColor:'#bbb',
        borderBottomWidth:1,
        marginVertical:20,
    }
}